version: "3.9"

services:
  app:
    container_name: frontend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3800:3000
    volumes:
      - ./code:/home/app
    environment:
      NGINX_AUTO_INDEX: "off"
      NGINX_CLIENT_MAX_BODY_SIZE: "40M"
      NGINX_DISABLE_SYMLINKS: "on"
      NGINX_PORT: 3000
      NGINX_PROXY_CONNECT_TIMEOUT: 60
      NGINX_PROXY_READ_TIMEOUT: 60
      NGINX_PROXY_SEND_TIMEOUT: 60
      NGINX_SENDFILE: "on"
      NODE_ENV: "development"
      REACT_API_DIGICOMMERCE_HOST: ""
